-- ⚠️ SUPERSEDED — this file is kept only as a pointer.
--
-- The schema now lives in versioned migrations:
--   supabase/migrations/20260722120000_init.sql   (tables + signup trigger)
--   supabase/migrations/20260722120100_rls.sql    (row level security)
-- and the catalog seed is generated from the app's data layer:
--   supabase/seed.sql   (regenerate with `npm run db:seed:generate`)
--
-- Apply locally:  supabase db reset      (migrations + seed)
-- Apply to cloud: supabase db push       (migrations only)
--
-- See SETUP.md → Supabase.
