// Generates supabase/seed.sql from the mock catalog (the single source of truth).
// Run with: npm run db:seed:generate
// Only relative runtime imports are used (type-only "@/..." imports are erased),
// so this runs under tsx without path-alias resolution.
import { writeFileSync } from "node:fs"
import { products } from "../src/lib/data/products"
import { categories } from "../src/lib/data/categories"

const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const jsonb = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`
const textArr = (items: string[]) =>
  `'{${items.map((i) => `"${i.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`).join(",")}}'`
const cents = (n: number) => Math.round(n * 100)
const nullable = (v: string | number | null | undefined) => (v == null ? "NULL" : String(v))

const lines: string[] = [
  "-- AUTO-GENERATED by scripts/generate-seed.mts — do not edit by hand.",
  "-- Run `supabase db reset` to apply migrations + this seed locally.",
  "",
]

lines.push("-- categories")
for (const c of categories) {
  lines.push(
    `insert into public.categories (id, slug, name, description, image_url) values ` +
      `(${q(c.id)}, ${q(c.slug)}, ${q(c.name)}, ${q(c.description)}, ${q(c.image)});`
  )
}
lines.push("")

lines.push("-- products")
for (const p of products) {
  lines.push(
    `insert into public.products (id, slug, name, tagline, description, price_cents, compare_at_cents, currency, ` +
      `materials, colors, sizes, print_time_hours, delivery_days_min, delivery_days_max, stock, trending, new_arrival, ` +
      `featured, license, size_cm, weight_grams, specifications, printing_settings, created_at) values (` +
      `${q(p.id)}, ${q(p.slug)}, ${q(p.name)}, ${q(p.tagline)}, ${q(p.description)}, ${cents(p.price.amount)}, ` +
      `${nullable(p.compareAtPrice ? cents(p.compareAtPrice.amount) : null)}, ${q(p.price.currency)}, ` +
      `${textArr(p.variants.materials)}, ${jsonb(p.variants.colors)}, ${textArr(p.variants.sizes)}, ` +
      `${p.printTimeHours}, ${p.deliveryDaysMin}, ${p.deliveryDaysMax}, ${p.stock}, ${p.trending ?? false}, ` +
      `${p.newArrival ?? false}, ${p.featured ?? false}, ${q(p.license)}, ${jsonb(p.sizeCm)}, ${p.weightGrams}, ` +
      `${jsonb(p.specifications)}, ${jsonb(p.printingSettings)}, ${q(p.createdAt)});`
  )
}
lines.push("")

lines.push("-- product_categories")
for (const p of products) {
  for (const catId of p.categoryIds) {
    lines.push(
      `insert into public.product_categories (product_id, category_id) values (${q(p.id)}, ${q(catId)}) on conflict do nothing;`
    )
  }
}
lines.push("")

lines.push("-- product_images")
for (const p of products) {
  p.images.forEach((url, i) => {
    lines.push(
      `insert into public.product_images (product_id, url, position) values (${q(p.id)}, ${q(url)}, ${i});`
    )
  })
}
lines.push("")

writeFileSync("supabase/seed.sql", lines.join("\n"))
console.log(`Wrote supabase/seed.sql — ${categories.length} categories, ${products.length} products.`)
